wandb_version: 1

min_samples_leaf:
  desc: null
  value:
  - 1
  - 2
  - 4
  - 6
  - 8
  - 10
  - 20
  - 30
min_impurity_decrease:
  desc: null
  value:
  - 0.0
  - 0.01
  - 0.05
  - 0.1
  - 0.15
  - 0.2
max_features:
  desc: null
  value:
  - auto
  - 0.8
  - 0.7
  - 0.6
  - 0.5
  - 0.4
max_depth:
  desc: null
  value:
  - null
  - 2
  - 4
  - 6
  - 8
  - 10
  - 20
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712572996.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
