wandb_version: 1

criterion:
  desc: null
  value:
  - entropy
  - gini
splitter:
  desc: null
  value:
  - random
  - best
min_weight_fraction_leaf:
  desc: null
  value:
  - 0.0
  - 0.0025
  - 0.005
  - 0.0075
  - 0.01
  - 0.05
min_samples_split:
  desc: null
  value:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 8
  - 10
min_samples_leaf:
  desc: null
  value:
  - 1
  - 0.01
  - 0.02
  - 0.03
  - 0.04
min_impurity_decrease:
  desc: null
  value:
  - 0.0
  - 0.0005
  - 0.005
  - 0.05
  - 0.1
  - 0.15
  - 0.2
max_leaf_nodes:
  desc: null
  value:
  - 10
  - 15
  - 20
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - null
max_features:
  desc: null
  value:
  - auto
  - 0.95
  - 0.9
  - 0.85
  - 0.8
  - 0.75
  - 0.7
max_depth:
  desc: null
  value:
  - null
  - 2
  - 4
  - 6
  - 8
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712567457.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
